[LPF-465]: Generate All Data Models Returned by the Service from the Swagger Documentation [Single point of truth] - Update Swagger spec to include security components
ministryofjustice/payforlegalaid pull request #60
Opened 2024-11-26 08:57 UTC by RobertBuczek

This pull request enhances the test coverage for the`ReportViewsDao` class and improves the OpenAPI specification for the project. The updates ensure better reliability, maintainability, and usability of the codebase and API.

The OpenAPI specification has been refined to provide a more advanced and detailed description of all API endpoints. Notable changes include the explicit linking of the `/reports` and `/reports/{id}` endpoints, making it easier for users to navigate between these related resources. The `/csv/{id}` endpoint documentation now includes detailed descriptions of expected behaviour and response formats. Additionally, OAuth2 Bearer token authentication is explicitly documented for all endpoints, emphasizing the importance of providing valid access tokens.

2024-11-26 14:01 UTC, ChrisCookOC commented on src/test/java/uk/gov/laa/gpfd/dao/ReportViewsDaoTest.java
> +    void shouldRetrieveDataWithSpecificParameters() {
This isn't testing that data is retrieved using specific parameters, its testing that you can send sql with parameters. 

shouldAllowQueriesWithParameters perhaps

2024-11-26 14:03 UTC, SineadCummings commented on src/test/java/uk/gov/laa/gpfd/dao/ReportViewsDaoTest.java
> +    void shouldHandleSQLInjectionAttemptGracefully() {
Need to discuss this test - not clear what is being tested here

2024-11-26 14:07 UTC, SineadCummings requested changes
Re ReportViewsDaoTest:
There are lots of tests relating to the content of the sql query. The sql is not being checked or used by any of these tests - we are mocking a response and confirming the mocked result is returned. Unclear on value of these tests, worth discussing

2024-11-26 14:08 UTC, SineadCummings commented on src/test/java/uk/gov/laa/gpfd/service/MetadataReportServiceTest.java
> +    void shouldLogInfoWhenReturningResponse() {
Is this testing logs or is this a placeholder?

2024-11-26 14:12 UTC, SineadCummings commented on src/test/java/uk/gov/laa/gpfd/service/MetadataReportServiceTest.java
> +    void shouldReturnResponseForBoundaryId() {
Unsure on purpose of this test - is this the same as shouldCreateReportResponseSuccessfully

2024-11-26 14:15 UTC, SineadCummings commented on src/test/java/uk/gov/laa/gpfd/service/MetadataReportServiceTest.java
> +    void shouldHandleNullUrlFieldGracefully() {
Url is not added to any of the above tests, this test is this the same as shouldCreateReportResponseSuccessfully

2024-11-27 08:52 UTC, smallmanj-moj approved these changes

2024-11-27 15:33 UTC, closed without merging